# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2

      - name: Prepare repository
        run: |
          echo "Fetching git tags for auto"
          git fetch --unshallow --tags
          echo "Installing fossa-cli for license scanning"
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: License Scan
        run: fossa analyze

      - name: Install dependencies
        run: yarn

      - name: Auto Info
        run: yarn auto info

      - name: Auto Release
        run: yarn release

    env:
      FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
