# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v2

      - name: 'Run FOSSA Scan'
        uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}

      - name: 'Run FOSSA Test'
        uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        with:
          api-key: ${{secrets.FOSSA_API_KEY}}
          run-tests: true

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      matrix:
        node: ['14', '15', '16', '17']
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Prepare repository
        run: |
          echo "Fetching git tags for auto"
          git fetch --unshallow --tags

      - name: Install dependencies
        run: yarn

      - name: Format
        run: yarn format:diff

      - name: Lint
        run: yarn lint

      - name: Run Tests
        run: yarn test

  release:
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Auto Info
        run: yarn auto info

      - name: Auto Release
        if: ${{ github.ref == 'refs/heads/master'}}
        run: yarn release

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
      TWITTER_CONSUMER_KEY_SECRET: ${{ secrets.TWITTER_CONSUMER_KEY_SECRET }}
      SKIP_PREFLIGHT_CHECK: true
